services:
  ubuntu-dev-refmerge:
    build: .
    container_name: dev-container-refmerge
    ports:
      - "127.0.0.1:3001:6901" # HTTPS access: https://localhost:3001/
    security_opt:
      - seccomp=unconfined # modern GUI desktop apps have issues with the latest Docker and syscall compatibility
    volumes:
      - dev_data_refmerge:/home/kasm-user # user directory
    environment:
      - VNCOPTIONS=-disableBasicAuth # uncomment for login (see below)
      - START_XFCE4=0 # /dockerstartup/vnc_startup.log
      - START_DE=kde5 # /dockerstartup/vnc_startup.log /usr/bin/startplasma-x11:
      # - VNC_PW=password # login: kasm_user, VNC_PW
    shm_size: "1gb" # we set this to 1 gig to prevent modern web browsers from crashing
    restart: on-failure

volumes:
  dev_data_refmerge:
